version: '3.8'
services:
  app:
    build: .
    command: sleep infinity
    volumes:
      - .:/app
    ports:
    - "3000:3000"
  database:
    image: postgres:16
    # ports:
    # - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpwd
      POSTGRES_DB: appdb

volumes:
  database-data: